// Mocks generated by Mockito 5.4.6 from annotations
// in food_safe/test/user_avatar_error_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;
import 'dart:typed_data' as _i6;

import 'package:flutter/foundation.dart' as _i2;
import 'package:food_safe/repositories/profile_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  @override
  _i2.ValueNotifier<int> get photoVersion => (super.noSuchMethod(
        Invocation.getter(#photoVersion),
        returnValue: _FakeValueNotifier_0<int>(
          this,
          Invocation.getter(#photoVersion),
        ),
        returnValueForMissingStub: _FakeValueNotifier_0<int>(
          this,
          Invocation.getter(#photoVersion),
        ),
      ) as _i2.ValueNotifier<int>);

  @override
  _i4.Future<String?> savePhoto(_i5.File? photoFile) => (super.noSuchMethod(
        Invocation.method(
          #savePhoto,
          [photoFile],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> removePhoto() => (super.noSuchMethod(
        Invocation.method(
          #removePhoto,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i5.File?> getPhoto() => (super.noSuchMethod(
        Invocation.method(
          #getPhoto,
          [],
        ),
        returnValue: _i4.Future<_i5.File?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.File?>.value(),
      ) as _i4.Future<_i5.File?>);

  @override
  _i4.Future<Object?> getPhotoData() => (super.noSuchMethod(
        Invocation.method(
          #getPhotoData,
          [],
        ),
        returnValue: _i4.Future<Object?>.value(),
        returnValueForMissingStub: _i4.Future<Object?>.value(),
      ) as _i4.Future<Object?>);

  @override
  _i4.Future<void> saveTempPhotoBytes(_i6.Uint8List? bytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTempPhotoBytes,
          [bytes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool hasPhoto() => (super.noSuchMethod(
        Invocation.method(
          #hasPhoto,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> setUserName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #setUserName,
          [name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setUserEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #setUserEmail,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getInitials() => (super.noSuchMethod(
        Invocation.method(
          #getInitials,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getInitials,
            [],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getInitials,
            [],
          ),
        ),
      ) as String);
}
